### ISSUE TITLE
Training with tensorflow-gpu

### ISSUE THREAD

**Issue by ani16** [Goldesel23/DCGAN-for-Bird-Generation#10]
Hi
@Goldesel23 

It is not working with tensorflow-gpu . If I uninstall tensorflow and install tensorflow-gpu, it throws error of no module named tensorflow. If I keep both, training goes with tensorflow cpu version.

How to resolve this. please help

**Comment by tensorfreitas** [comment]
Hi @ani16 it is probably better if you try to ask for help on the keras/tensorflow github, since this is certainly a problem with your tensorflow-gpu instalation. Best of luck!

**Comment by ani16** [comment]
Hi
@ Goldesel..

Can You please tell what have you done to make it work with tensorflow-gpu. Have you made any changes in the code or something with installation version.  I have installed tensorflow-gpu 1.14. Still it does not work.

**Comment by ani16** [comment]
Hi

This repo does not work with tensorflow - GPU.. How do you manage. You kept on closing my issue without answering. Please do answer
