### ISSUE TITLE
Fails to work with Tensorflow-GPU

### ISSUE THREAD

**Issue by ani16** [Goldesel23/DCGAN-for-Bird-Generation#11]
Hi
@ Goldesel..

Can You please tell what have you done to make it work with tensorflow-gpu. Have you made any changes in the code or something with installation version. I have installed tensorflow-gpu 1.14. Still it does not work.

My tensoflow-gpu is successfully installed in virtual env with pip. Its my request not to close the issue before it is solved.

**Comment by tensorfreitas** [comment]
Already answered on #10
