### ISSUE TITLE
how to generate the images using the trained model

### ISSUE THREAD

**Issue by wenouyang** [Goldesel23/DCGAN-for-Bird-Generation#2]
Hi Tiago,

Thanks for sharing the code. I have two questions, thank you for your help.

1) If I would like to train the model using my own dataset, are there any requirements for the image data set itself, such as size, RGB/gray, etc?
2) After training the model, how to use the code to generate the new images?

Thanks

**Comment by tensorfreitas** [comment]
Hi!

1. The code is expecting RGB images, and resizes them automatically (to 64x64). You should be able to adapt the code easily to a different dataset. 
2. The code currently saves the images automatically each epoch (similarly to the ones shown in the readme.md file)

Feel free to reach by if you have any questions!

**Comment by wenouyang** [comment]
Hi Tiago,

Thanks for the reply. Regarding the second question,  you mentioned that `The code currently saves the images automatically each epoch `, my understanding is that this is related to the training process. If the training process has finished, and the model has been trained. How to use this saved model to automatically generating the new images?

**Comment by tensorfreitas** [comment]
After Loading the model, you'll just need to pass the generator to some random noise with the size of the images you want to generate:

`noise = np.random.normal(0, 1, size=(nr_images_to_generate,) + (1, 1, 100))

generated_images = generator.predict(noise)`

Remember that the images need to re-normalized to 0-255 afterwards.
