### ISSUE TITLE
DCGAN's code for test

### ISSUE THREAD

**Issue by HwaiHo-0552** [Goldesel23/DCGAN-for-Bird-Generation#3]
Could you share the code for test ?  I can not code correctly.
Thanks.

**Comment by tensorfreitas** [comment]
Could you explain what have you tried? If you downloaded the dataset and change the path of it in main() you should be ready for training.

**Comment by HwaiHo-0552** [comment]
training over and save model as 'xxxx.h5', For testing that generate some new images, as follow(1)load the 'xxxx.h5' before test  in Generator Network (2)generate some new images 
I just know about the processing of GAN, but can not how to code the testing work.
Thanks.

**Comment by tensorfreitas** [comment]
You can load the model and simulate the code of line 209 that generates new images from noise.

**Comment by HwaiHo-0552** [comment]
Thank you. @Goldesel23

**Comment by tensorfreitas** [comment]
I am glad I helped. I'll close the issue. Feel free to reopen it if you have any related question!
