### ISSUE TITLE
Generator per Discriminator training steps

### ISSUE THREAD

**Issue by amw5g** [Goldesel23/DCGAN-for-Bird-Generation#6]
Howdy @Goldesel23 !  I'm just learning about GANs, and reading about tuning the number of generator training steps per discriminator training steps (GpD).  As you've written, can you please confirm that it's 2-to-1 here?  That is, within each epoch, the discriminator trains for 1 *batch_size then the generator follows by training for 2*batch_size.  Do I have that correct? I intend to adjust to allow for user-defined GpD, but wanted to make sure I've read your implementation correctly.

**Comment by tensorfreitas** [comment]
Hi !

During the first 25 epochs the discriminator is updated 100 times for each generator update. In the other epochs the default value is 5 to 1. Each 500 epochs, the discriminator is updated 100 times for each generator update. 

Best Regads!
