### ISSUE TITLE
Training with own datasets

### ISSUE THREAD

**Issue by ani16** [Goldesel23/DCGAN-for-Bird-Generation#7]
Hi

@Goldesel23
I would like to train with face images dataset. Can you please help me how to do with your repo. I want to use your repository and mention your repository in my work as citation .

**Comment by tensorfreitas** [comment]
Hi! 

If you point the ImageDataGenerator to the folder with the images of faces it should be straightforward! 

Best Regards!

**Comment by ani16** [comment]
Thanks for reply. Yes I did it today already. Its getting trained but
performance is poor. Can you tell me if I want to generate images for only
one category, then how long should be my training data. With 100 images
it's not giving satisfactory results.

**Comment by tensorfreitas** [comment]
I don't know if 100 images are good enough for good results. There are more modern GANs that will perform a lot better ant with better stability. Try increasing the number of images (like with the CelebA dataset) or try more modern GAN architectures.

**Comment by ani16** [comment]
Thanks for reply. With 100 images it does not give good performance.
In fact you have tried with 11k,images for better results.

Do have any other code with better gans to train with few images and get
good results.

**Comment by ani16** [comment]
Hi

@Goldesel23 

I am going to try with celebA dataset of faces. Can you tell me how much time it will take to train. As it is CPU based repository, I dont know how much it will take?

Do you have provision for GPU also

**Comment by ani16** [comment]
Hi

I am trying with celebA dataset, it's giving good results. But see training
takes a lot of time. Do you have any provision to restart with saved
weights and resume training from there. Does it have any command like that.

Atleast it will take 2 days.

**Comment by ani16** [comment]
Hi

Please do reply is there any option to restart with saved weights.

**Comment by tensorfreitas** [comment]
Hi! Since the code is all in keras, you can do it like just any other keras code! This implementation does not have directly that possibility but is definitely doable.

**Comment by ani16** [comment]
Thanks for your reply. But can you help me to do this.

I am training celeb dataset and result are coming pretty good. I will cite
your work in my paper too. Thanks

**Comment by tensorfreitas** [comment]
The model weights for the generator and discriminator are already being saved in h5 files. To resume training you just need to load them as any other keras model: https://keras.io/models/about-keras-models/

Since this is related to general keras and not the project I will close the issue. 

Best of luck with your project!

**Comment by ani16** [comment]
Thanks so much for reply. But I am doing same for resuming training, but
weights not getting loaded. Can you tell me exact where should I place load
model?  It will be very helpful for me
