### ISSUE TITLE
Training on Nvidia k40

### ISSUE THREAD

**Issue by ani16** [Goldesel23/DCGAN-for-Bird-Generation#8]
Hi

I would like to train dataset with K40 GPU. Is is possible with the your repository. I think tensorflow-gpu install will do? Or do You have some other dependencies or any particular version of tensorflow-gpu. I am having cuda-7.5 installed on Ubuntu 16.04 with K40 GPU.

Thanks in advance.

**Comment by tensorfreitas** [comment]
Hi,

Installing tensorflow-gpu will be enough for running in the K40.

**Comment by ani16** [comment]
Thanks

**Comment by ani16** [comment]
Hi

I have successfully installed tensorflow-gpu but still training is happening with tensorflow cpu version. There is no difference in training time. How to train model with gpu version of tensorflow and keras.

**Comment by ani16** [comment]
Hi @Goldesel23 ... It is not working with tensorflow-gpu . If I uninstall tensorflow and install tensorflow-gpu, it throws error of no module named tensorflow. If I keep both, training goes with tensorflow cpu version.

How to resolve this. please help.
