### ISSUE TITLE
Training dataset with one category of data

### ISSUE THREAD

**Issue by ani16** [Goldesel23/DCGAN-for-Bird-Generation#9]
Hi
@Goldesel23 . I took celebA dataset. it has approx 10k categories. As it is Conditional GAN, I labelled all taken images as 1 means single labeled data is feeded for training. Does it has any problem in quality of results at the end as i dont train with multiple labels. My resullts are pretty good with this dataset but still little blur. Does it has anything to do with single labeled data taken?  

Thanks in advance

**Comment by ani16** [comment]
Moreover images are very nicely cropped and aligned. There is no issue with quality of input data.

**Comment by tensorfreitas** [comment]
The code is optimized for using a single class. If you want to include different classes you may want to search for conditional GANs implementations across github! Try to train for a little more time, if the blur persists, try to implement more modern GANs that should lead you to more realistic images.

**Comment by ani16** [comment]
Thanks for reply. Yes I am using single class but still some blurness is
there. Can you name some modern GANs.

And Dcgan which you have implemented is also conditional GAN I guess. The
paper which you referred is deep convolutional conditional GAN. Am I right?

**Comment by ani16** [comment]
One more thing, you have also taken different classes of birds and got
result. But here you are saying code is optimised with single class, I did
not get it. Please help me.
